show raw response on error for full details just like Slack's API tester shows
currently, in __init__.BaseAPI() , on an error, only the error text is shown:

e.g. "slacker.Error: missing_scope"

which hides the detailed reasons for the error, 'coz of usage of just "error.text", instead of "error.raw"

this feature is to show the full error details, so the users knows all the reasons behind the error, just like Slack's API "Tester" shows the detailed results for errors:

e.g. slacker.Error: '{"ok": false,"error": "missing_scope","needed": "users:read","provided": "admin,identify"}

pgm flow happens like so:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Python37\Scripts\backup_slack-script.py", line 11, in <module>
    load_entry_point('backup-slack', 'console_scripts', 'backup_slack')()
  File "d:\amitava\slackbkup\src\backup-slack\backup_slack.py", line 232, in main
    slack = SlackHistory(token=args.token)
  File "d:\amitava\slackbkup\src\backup-slack\backup_slack.py", line 137, in __init__
    self.usernames = self._fetch_user_mapping()
  File "d:\amitava\slackbkup\src\backup-slack\backup_slack.py", line 175, in _fetch_user_mapping
    for u in self.slack.users.list().body['members']}
  File "c:\program files (x86)\python37\lib\site-packages\slacker\__init__.py", line 332, in list
    return self.get('users.list', params={'presence': int(presence)})
  File "c:\program files (x86)\python37\lib\site-packages\slacker\__init__.py", line 121, in get
    api, **kwargs
  File "c:\program files (x86)\python37\lib\site-packages\slacker\__init__.py", line 103, in _request
    raise Error(response.raw)
slacker.Error: {"ok":false,"error":"missing_scope","needed":"users:read","provided":"admin,identify"}